### ISSUE TITLE
Help required - to see my changes on my own machine

### ISSUE THREAD

**Issue by rahul1409** [gojko/bugmagnet#10]
Hi - I am Rahul, a Test professional leading a test team. I found your tool very useful, however I need to amend it with my set of values. Please guide me and tell me the process of doing that on my machine.

I am not having an indepth knowledge of programming or Unix systems, however, if you tell me, I will do that task.

Thanks
Rahul

**Comment by gojko** [comment]
If you're using Chrome, the latest version has a "configure" button at the bottom which you can click to get a dialog for loading your values into bugmagnet. this allows you to extend bugmagnet with your configuration without any programming tools or knowledge. See https://github.com/gojko/bugmagnet#customising for more information and some example files

**Comment by rahul1409** [comment]
Great great, I did it on CHrome.

I was originally trying on Firefox, how to do it on FF ?

Many Thanks
Rahul

**Comment by gojko** [comment]
the FF version is not updated yet for that feature, it should be added soon. on FF you have to modify the config.json file and then follow the instructions for running from a local machine (see https://github.com/gojko/bugmagnet#contributing-and-extending-code).
