### ISSUE TITLE
The bugmagnet does not send events to inputs

### ISSUE THREAD

**Issue by bkostrowiecki** [gojko/bugmagnet#12]
Hi there,

very nice job with this addon. Our testers try to use your plugin and they find it very 	
comfortable.

But we encountred one problem. We cannot use BugMagnet when our textarea or inputs have attached some event listeners in JavaScript. I am talking especially about events like 'paste', 'keyup', 'keydown'. Events seems not to be triggered at all. It means that we cannot use BugMagnet when we have complex UI. 

Have you ever thought about adding feature like triggering events? It would be awesome, if a tester would choose from modes like 'paste' / 'key events'.

**Comment by gojko** [comment]
it sends the input event. keyup/keydown etc are good for testing individual characters, not whole sentences. plus you can get inputs without keydowns (eg paste). so in short, I don't need that, but if it's useful to you, fork and change it.
