### ISSUE TITLE
Inject mode with draft-js

### ISSUE THREAD

**Issue by malykhinvi** [gojko/bugmagnet#18]
By default bug magnet works in in "Inject value" mode. As I understand in this mode, if we try to insert value in contenteditable element, it will replace the innerText of that element.
In some wysiwyg editors, e.g. based on draft-js, there is a complex structure inside `contenteditable` div. If bugmagent replaces all DOM nodes with text, widget stops working.

**Steps to reproduce**
1. Open https://draftjs.org/
2. Insert any value in "Inject value" mode
3. Try to remove inserted text.

**Actual result:** you can not remove inserted text, most of editor features does not work anymore.
**Expected result:** don't know actually.

It worth mentioning, that in "Simulate copy/paste" mode everything works like a charm. Probably bugmagnet should not replace the content, if there are DOM nodes inside contenteditable element? Or suggest user to switch to copy/paste simulation mode?

**Comment by gojko** [comment]
thanks for reporting this. simulate copy/paste is already intended for this kind of work, so unless there is some specific work for bugmagnet, I'll close the issue
